image: bitbucketpipelines/scala-sbt:scala-2.12

pipelines:
  custom:
    create-download:
      - step:
          script:
            - apt-get update
            - apt-get install -y openjfx
            - sbt assembly
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/scala-2.12/mco2-assembly-2.0.0-SNAPSHOT.jar"
